[profile.default]
src = "src"
out = "out"
libs = ["lib"]
#via_ir = true
fs_permissions = [{ access = "read", path = "out-optimized" }, { access = "read-write", path = "gas_calculations" }]
allow_paths = ["*", "/"]

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
